name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gradle

      - name: Test
        run: ./gradlew test

  deploy-docs:
    runs-on: ubuntu-latest
    needs: test  # This ensures that the deploy-docs job runs only if the test job succeeds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17' # or the version you are using

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and generate documentation
        run: ./gradlew dokkaHtml

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch origin
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          cp -r ../docs/* .
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m 'Deploy documentation [skip ci]'
            git push origin gh-pages
          fi
